# Generated by Django 3.1.2 on 2021-04-03 17:30

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='')),
                ('product_name', models.CharField(max_length=50)),
                ('product_id', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=150)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('city', models.CharField(max_length=150)),
                ('pin_code', models.BigIntegerField()),
                ('latitude', models.CharField(default='29.976480', max_length=9)),
                ('longitude', models.CharField(default='31.131302', max_length=9)),
                ('size', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'XS'), (2, 'S'), (3, 'M'), (4, 'L'), (5, 'XL'), (6, 'XXL')], default='S', max_length=11)),
                ('product_det', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.productdet')),
            ],
        ),
    ]
